# Generated by Django 5.2 on 2025-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("apple", "Apple"),
                    ("django", "Email/Password"),
                ],
                db_index=True,
                default="django",
                max_length=30,
            ),
        ),
    ]
