# Generated by Django 5.2 on 2025-04-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_blazelyprofile_alter_grouplist_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='taskstep',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
