# Generated by Django 5.2 on 2025-04-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_rename_created_date_in_task_and_task_step_to_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="todo.tasklist",
            ),
        ),
    ]
