# Generated by Django 5.2 on 2025-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_make_task_list_not_nullable_in_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="note",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
