# Generated by Django 5.2 on 2025-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_make_note_nullable_in_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="blazelyprofile",
            name="profile_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
