# Generated by Django 5.2 on 2025-05-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_add_field_profile_picture_url_to_blazelyprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.AddConstraint(
            model_name='grouplist',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_group_list'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_label'),
        ),
        migrations.AddConstraint(
            model_name='tasklist',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_task_list'),
        ),
    ]
