# Generated by Django 5.2 on 2025-05-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_created_by_label_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='emoji',
            field=models.CharField(default='📃', max_length=100, null=True),
        ),
    ]
