# Generated by Django 5.2 on 2025-05-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_tasklist_add_emoji_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_date',
            field=models.DateTimeField(null=True),
        ),
    ]
