# Generated by Django 5.2.3 on 2025-06-15 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grouplists', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('archived', models.BooleanField(default=False)),
                ('emoji', models.CharField(default='📃', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='grouplists.grouplist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='profiles.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'owner'), name='unique_task_list')],
            },
        ),
    ]
